### ISSUE TITLE
Dates are not ordered on the default view

### ISSUE THREAD

**Issue by NovAti0n** [NovAti0n/MOOdle#17]
All is in the title. (This might be a problem with the postgre adaptation)

https://moodle.novation.dev/?chart=0

**Comment by obiwac** [comment]
I think it is an issue with the adaptation, we'd have noticed it earlier if not 😄

**Comment by obiwac** [comment]
no, sorry

**Comment by obiwac** [comment]
![image](https://github.com/NovAti0n/MOOdle/assets/11079650/615072b0-18a1-4693-9bfc-3c9e52a9235c)
